export async function getTableData(page = 1, perPage = 10, params = {}) {
    const data = [
        {
            name: "Person 1",
            manager_email: "person1@example.com",
            enps: 74,
            max_score: 100,
            date_of_joining: "2019-03-02",
            tenure_in_current_company: "6 months",
            total_attrition: 3,
            tenure: "11 months",
        },
        {
            name: "Person 2",
            manager_email: "person2@example.com",
            enps: 65,
            max_score: 100,
            date_of_joining: "2020-10-12",
            tenure_in_current_company: "8 months",
            total_attrition: 5,
            tenure: "3 months",
        },
        {
            name: "Person 3",
            manager_email: "person3@example.com",
            enps: 80,
            max_score: 100,
            date_of_joining: "2021-06-20",
            tenure_in_current_company: "2 months",
            total_attrition: 4,
            tenure: "7 months",
        },
        {
            name: "Person 4",
            manager_email: "person4@example.com",
            enps: 78,
            max_score: 100,
            date_of_joining: "2018-12-14",
            tenure_in_current_company: "9 months",
            total_attrition: 2,
            tenure: "5 months",
        },
        {
            name: "Person 5",
            manager_email: "person5@example.com",
            enps: 68,
            max_score: 100,
            date_of_joining: "2020-02-10",
            tenure_in_current_company: "5 months",
            total_attrition: 3,
            tenure: "8 months",
        },
        {
            name: "Person 6",
            manager_email: "person6@example.com",
            enps: 90,
            max_score: 100,
            date_of_joining: "2017-08-01",
            tenure_in_current_company: "4 months",
            total_attrition: 6,
            tenure: "9 months",
        },
        {
            name: "Person 7",
            manager_email: "person7@example.com",
            enps: 82,
            max_score: 100,
            date_of_joining: "2021-01-15",
            tenure_in_current_company: "3 months",
            total_attrition: 2,
            tenure: "6 months",
        },
        {
            name: "Person 8",
            manager_email: "person8@example.com",
            enps: 77,
            max_score: 100,
            date_of_joining: "2019-05-20",
            tenure_in_current_company: "4 months",
            total_attrition: 4,
            tenure: "7 months",
        },
        {
            name: "Person 9",
            manager_email: "person9@example.com",
            enps: 88,
            max_score: 100,
            date_of_joining: "2020-11-08",
            tenure_in_current_company: "2 months",
            total_attrition: 3,
            tenure: "10 months",
        },
        {
            name: "Person 10",
            manager_email: "person10@example.com",
            enps: 71,
            max_score: 100,
            date_of_joining: "2018-04-15",
            tenure_in_current_company: "1 month",
            total_attrition: 5,
            tenure: "11 months",
        },
        {
            name: "Person 11",
            manager_email: "person11@example.com",
            enps: 85,
            max_score: 100,
            date_of_joining: "2021-03-11",
            tenure_in_current_company: "3 months",
            total_attrition: 6,
            tenure: "6 months",
        },
        {
            name: "Person 12",
            manager_email: "person12@example.com",
            enps: 79,
            max_score: 100,
            date_of_joining: "2017-12-25",
            tenure_in_current_company: "7 months",
            total_attrition: 3,
            tenure: "8 months",
        },
        {
            name: "Person 13",
            manager_email: "person13@example.com",
            enps: 76,
            max_score: 100,
            date_of_joining: "2019-09-14",
            tenure_in_current_company: "4 months",
            total_attrition: 4,
            tenure: "5 months",
        },
        {
            name: "Person 14",
            manager_email: "person14@example.com",
            enps: 92,
            max_score: 100,
            date_of_joining: "2020-03-30",
            tenure_in_current_company: "8 months",
            total_attrition: 2,
            tenure: "6 months",
        },
        {
            name: "Person 15",
            manager_email: "person15@example.com",
            enps: 81,
            max_score: 100,
            date_of_joining: "2018-07-05",
            tenure_in_current_company: "5 months",
            total_attrition: 1,
            tenure: "9 months",
        },
        {
            name: "Person 16",
            manager_email: "person16@example.com",
            enps: 74,
            max_score: 100,
            date_of_joining: "2021-06-22",
            tenure_in_current_company: "6 months",
            total_attrition: 2,
            tenure: "7 months",
        },
        {
            name: "Person 17",
            manager_email: "person17@example.com",
            enps: 89,
            max_score: 100,
            date_of_joining: "2020-05-12",
            tenure_in_current_company: "3 months",
            total_attrition: 4,
            tenure: "11 months",
        },
        {
            name: "Person 18",
            manager_email: "person18@example.com",
            enps: 67,
            max_score: 100,
            date_of_joining: "2019-11-18",
            tenure_in_current_company: "5 months",
            total_attrition: 5,
            tenure: "10 months",
        },
        {
            name: "Person 19",
            manager_email: "person19@example.com",
            enps: 84,
            max_score: 100,
            date_of_joining: "2017-02-20",
            tenure_in_current_company: "2 months",
            total_attrition: 4,
            tenure: "12 months",
        },
        {
            name: "Person 20",
            manager_email: "person20@example.com",
            enps: 77,
            max_score: 100,
            date_of_joining: "2020-09-28",
            tenure_in_current_company: "1 month",
            total_attrition: 3,
            tenure: "5 months",
        },
        {
            name: "Person 21",
            manager_email: "person21@example.com",
            enps: 73,
            max_score: 100,
            date_of_joining: "2016-04-18",
            tenure_in_current_company: "7 months",
            total_attrition: 2,
            tenure: "8 months",
        },
        {
            name: "Person 22",
            manager_email: "person22@example.com",
            enps: 88,
            max_score: 100,
            date_of_joining: "2019-07-25",
            tenure_in_current_company: "4 months",
            total_attrition: 3,
            tenure: "10 months",
        },
        {
            name: "Person 23",
            manager_email: "person23@example.com",
            enps: 75,
            max_score: 100,
            date_of_joining: "2018-11-02",
            tenure_in_current_company: "3 months",
            total_attrition: 5,
            tenure: "12 months",
        },
        {
            name: "Person 24",
            manager_email: "person24@example.com",
            enps: 91,
            max_score: 100,
            date_of_joining: "2017-05-14",
            tenure_in_current_company: "6 months",
            total_attrition: 1,
            tenure: "11 months",
        },
        {
            name: "Person 25",
            manager_email: "person25@example.com",
            enps: 80,
            max_score: 100,
            date_of_joining: "2020-08-10",
            tenure_in_current_company: "2 months",
            total_attrition: 3,
            tenure: "7 months",
        },
        {
            name: "Person 26",
            manager_email: "person26@example.com",
            enps: 87,
            max_score: 100,
            date_of_joining: "2018-06-19",
            tenure_in_current_company: "9 months",
            total_attrition: 2,
            tenure: "6 months",
        },
        {
            name: "Person 27",
            manager_email: "person27@example.com",
            enps: 69,
            max_score: 100,
            date_of_joining: "2021-01-05",
            tenure_in_current_company: "5 months",
            total_attrition: 6,
            tenure: "3 months",
        },
        {
            name: "Person 28",
            manager_email: "person28@example.com",
            enps: 77,
            max_score: 100,
            date_of_joining: "2019-10-22",
            tenure_in_current_company: "1 month",
            total_attrition: 4,
            tenure: "11 months",
        },
        {
            name: "Person 29",
            manager_email: "person29@example.com",
            enps: 82,
            max_score: 100,
            date_of_joining: "2016-03-17",
            tenure_in_current_company: "6 months",
            total_attrition: 2,
            tenure: "9 months",
        },
        {
            name: "Person 30",
            manager_email: "person30@example.com",
            enps: 71,
            max_score: 100,
            date_of_joining: "2020-12-09",
            tenure_in_current_company: "3 months",
            total_attrition: 5,
            tenure: "8 months",
        },
        {
            name: "Person 31",
            manager_email: "person31@example.com",
            enps: 85,
            max_score: 100,
            date_of_joining: "2019-02-28",
            tenure_in_current_company: "2 months",
            total_attrition: 4,
            tenure: "12 months",
        },
        {
            name: "Person 32",
            manager_email: "person32@example.com",
            enps: 66,
            max_score: 100,
            date_of_joining: "2017-09-13",
            tenure_in_current_company: "4 months",
            total_attrition: 6,
            tenure: "7 months",
        },
        {
            name: "Person 33",
            manager_email: "person33@example.com",
            enps: 90,
            max_score: 100,
            date_of_joining: "2021-03-19",
            tenure_in_current_company: "5 months",
            total_attrition: 3,
            tenure: "6 months",
        },
        {
            name: "Person 34",
            manager_email: "person34@example.com",
            enps: 79,
            max_score: 100,
            date_of_joining: "2016-12-05",
            tenure_in_current_company: "8 months",
            total_attrition: 4,
            tenure: "10 months",
        },
        {
            name: "Person 35",
            manager_email: "person35@example.com",
            enps: 84,
            max_score: 100,
            date_of_joining: "2020-05-22",
            tenure_in_current_company: "1 month",
            total_attrition: 5,
            tenure: "11 months",
        },
        {
            name: "Person 36",
            manager_email: "person36@example.com",
            enps: 68,
            max_score: 100,
            date_of_joining: "2017-07-30",
            tenure_in_current_company: "7 months",
            total_attrition: 2,
            tenure: "8 months",
        },
        {
            name: "Person 37",
            manager_email: "person37@example.com",
            enps: 76,
            max_score: 100,
            date_of_joining: "2018-08-14",
            tenure_in_current_company: "6 months",
            total_attrition: 3,
            tenure: "9 months",
        },
        {
            name: "Person 38",
            manager_email: "person38@example.com",
            enps: 89,
            max_score: 100,
            date_of_joining: "2019-01-16",
            tenure_in_current_company: "2 months",
            total_attrition: 4,
            tenure: "7 months",
        },
        {
            name: "Person 39",
            manager_email: "person39@example.com",
            enps: 81,
            max_score: 100,
            date_of_joining: "2021-04-08",
            tenure_in_current_company: "3 months",
            total_attrition: 1,
            tenure: "10 months",
        },
        {
            name: "Person 40",
            manager_email: "person40@example.com",
            enps: 72,
            max_score: 100,
            date_of_joining: "2020-09-06",
            tenure_in_current_company: "4 months",
            total_attrition: 5,
            tenure: "6 months",
        },
        {
            name: "Person 41",
            manager_email: "person41@example.com",
            enps: 87,
            max_score: 100,
            date_of_joining: "2018-11-11",
            tenure_in_current_company: "9 months",
            total_attrition: 2,
            tenure: "12 months",
        },
        {
            name: "Person 42",
            manager_email: "person42@example.com",
            enps: 70,
            max_score: 100,
            date_of_joining: "2019-06-04",
            tenure_in_current_company: "5 months",
            total_attrition: 6,
            tenure: "5 months",
        },
        {
            name: "Person 43",
            manager_email: "person43@example.com",
            enps: 78,
            max_score: 100,
            date_of_joining: "2017-03-26",
            tenure_in_current_company: "7 months",
            total_attrition: 3,
            tenure: "9 months",
        },
        {
            name: "Person 44",
            manager_email: "person44@example.com",
            enps: 92,
            max_score: 100,
            date_of_joining: "2020-07-21",
            tenure_in_current_company: "2 months",
            total_attrition: 1,
            tenure: "8 months",
        },
        {
            name: "Person 45",
            manager_email: "person45@example.com",
            enps: 83,
            max_score: 100,
            date_of_joining: "2018-05-30",
            tenure_in_current_company: "6 months",
            total_attrition: 4,
            tenure: "7 months",
        },
        {
            name: "Person 46",
            manager_email: "person46@example.com",
            enps: 75,
            max_score: 100,
            date_of_joining: "2019-10-05",
            tenure_in_current_company: "3 months",
            total_attrition: 5,
            tenure: "11 months",
        },
        {
            name: "Person 47",
            manager_email: "person47@example.com",
            enps: 91,
            max_score: 100,
            date_of_joining: "2016-02-19",
            tenure_in_current_company: "4 months",
            total_attrition: 2,
            tenure: "6 months",
        },
        {
            name: "Person 48",
            manager_email: "person48@example.com",
            enps: 74,
            max_score: 100,
            date_of_joining: "2021-03-12",
            tenure_in_current_company: "5 months",
            total_attrition: 3,
            tenure: "12 months",
        },
        {
            name: "Person 49",
            manager_email: "person49@example.com",
            enps: 88,
            max_score: 100,
            date_of_joining: "2020-01-01",
            tenure_in_current_company: "6 months",
            total_attrition: 4,
            tenure: "10 months",
        },
        {
            name: "Person 50",
            manager_email: "person50@example.com",
            enps: 85,
            max_score: 100,
            date_of_joining: "2014-07-15",
            tenure_in_current_company: "1 month",
            total_attrition: 2,
            tenure: "10 months",
        },
    ];


    let filteredData = [...data];
    if (params?.search) {
        filteredData = [...filteredData].filter(
            (item) =>
                item.name.toLowerCase().includes(params?.search?.toLowerCase()) ||
                item.manager_email.toLowerCase().includes(params?.search?.toLowerCase())
        );
    }

    console.log(params);
    if (params?.sorting_key && ["ascending", "descending"].includes(params?.sorting_direction)) {
        filteredData = [...filteredData].sort((a, b) => {
            if (a[params?.sorting_key] < b[params?.sorting_key]) return params?.sorting_direction === "ascending" ? -1 : 1;
            if (a[params?.sorting_key] > b[params?.sorting_key]) return params?.sorting_direction === "ascending" ? 1 : -1;
            return 0;
        });
    }
    const totalItems = filteredData.length;
    const totalPages = Math.ceil(totalItems / perPage);
    const startIndex = (page - 1) * perPage;
    const paginatedData = filteredData.slice(startIndex, startIndex + perPage);

    const columns = [
        { label: "Name", data_key: "name", is_fixed: true, is_sorting: true },
        { label: "Manager Email", data_key: "manager_email", is_fixed: false, is_sorting: false },
        { label: "ENPS", data_key: "enps", is_fixed: false, is_sorting: true },
        { label: "Max Score", data_key: "max_score", is_fixed: false, is_sorting: true },
        { label: "Date of Joining", data_key: "date_of_joining", is_fixed: false, is_sorting: true },
        { label: "Tenure in Current Company", data_key: "tenure_in_current_company", is_fixed: false, is_sorting: true },
        { label: "Total Attrition", data_key: "total_attrition", is_fixed: false, is_sorting: false },
        { label: "Tenure", data_key: "tenure", is_fixed: false, is_sorting: true },
    ];

    return {
        columns,
        data: paginatedData,
        totalItems,
        totalPages
    };
}
